// enums
int C_IBS_NOK = 0;
int C_IBS_OK = 1;

int N_VALVE_CROSS = 0;
int N_VALVE_DIAG = 1;
int N_MANUAL = 2;
int N_AUTOMATIK = 3;

int STATE_OUTSIDE_DEADZONE = 0;
int STATE_WITHIN_DEADZONE = 1;
int STATE_MOVE_UP = 3;
int STATE_MOVE_DOWN = 4;

